"""Write site/example-report.html: the report `ranwhat demo --html` makes,
with the head a page on this site needs and a line saying what it is.

    python3 scripts/example_report.py

tests/test_site_claims.py regenerates it and fails when the published copy
no longer matches what the tool produces, so a catalogue change that moves
a score cannot leave the site showing the old one.
"""
import os
import re
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
OUT = os.path.join(ROOT, "site", "example-report.html")

# The same head every other page carries: share tags, so a link to the
# example unfurls like the rest of the site, and the breadcrumb the search
# tests require of every interior page.
TITLE = "Example report | ranwhat"
DESCRIPTION = ("A full ranwhat authority report on an example support agent: scores, exposure, and every finding, exactly as the CLI writes it.")
URL = "https://ranwhat.com/example-report"
HEAD = """<title>{t}</title>
<meta name="description" content="{d}">
<link rel="canonical" href="{u}">
<link rel="icon" href="/favicon-32.png?v=2" sizes="32x32" type="image/png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="ranwhat">
<meta property="og:url" content="{u}">
<meta property="og:title" content="{t}">
<meta property="og:description" content="{d}">
<meta property="og:image" content="https://ranwhat.com/og-c85b8f42.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="ranwhat: find out what your agents actually did">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@ranwhatcom">
<meta name="twitter:image" content="https://ranwhat.com/og-c85b8f42.png">
<meta name="twitter:title" content="{t}">
<meta name="twitter:description" content="{d}">
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"ranwhat","item":"https://ranwhat.com/"}},{{"@type":"ListItem","position":2,"name":"Example report","item":"{u}"}}]}}</script>""".format(
    t=TITLE, d=DESCRIPTION, u=URL)

BANNER = ("<p style=\"margin:0 0 22px;font-size:13px;color:var(--muted)\">"
          "An example, not your data: this is what <code>uvx ranwhat demo "
          "--html report.html</code> writes for a bundled sample agent. "
          "<a style=\"color:var(--ink)\" href=\"/scan\">What the scores mean</a> &middot; "
          "<a style=\"color:var(--ink)\" href=\"/install\">Run it on your own</a></p>\n")

# The timestamp changes on every run and says nothing about the content.
GENERATED = re.compile(r"Generated [^<·]*·")


def build():
    from ranwhat import catalog
    from ranwhat.cli import run_scan, _bundled
    from ranwhat.html_report import build_html

    # The bundled catalogue only. A feed cached under RANWHAT_HOME on the
    # machine running this would otherwise rate the demo's scopes, and the
    # page would show that machine's subscription, not what users get.
    argv, sys.argv = sys.argv, ["uvx ranwhat"]
    home = os.environ.get("RANWHAT_HOME")
    empty = tempfile.mkdtemp(prefix="ranwhat-example-")
    os.environ["RANWHAT_HOME"] = empty
    catalog.reset_feed_cache()
    try:
        html = build_html(run_scan(_bundled("support-copilot.json")))
    finally:
        sys.argv = argv
        if home is None:
            os.environ.pop("RANWHAT_HOME", None)
        else:
            os.environ["RANWHAT_HOME"] = home
        catalog.reset_feed_cache()
        shutil.rmtree(empty, ignore_errors=True)
    html = GENERATED.sub("Generated by ranwhat demo ·", html)
    html = re.sub(r"<title>[^<]*</title>", lambda m: HEAD, html, count=1)
    return re.sub(r"(<body[^>]*>\s*(?:<div[^>]*>\s*)?)", lambda m: m.group(1) + BANNER,
                  html, count=1)


if __name__ == "__main__":
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(build())
    print("wrote", os.path.relpath(OUT, ROOT))
