"""Write site/example-report.html: the report `ranwhat demo --html` makes,
with the head a page on this site needs and a line saying what it is.

    python3 scripts/example_report.py

tests/test_site_claims.py regenerates it and fails when the published copy
no longer matches what the tool produces, so a catalogue change that moves
a score cannot leave the site showing the old one.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
OUT = os.path.join(ROOT, "site", "example-report.html")

HEAD = """<title>Example report | ranwhat</title>
<meta name="description" content="A full ranwhat authority report on an example support agent: scores, exposure, and every finding, exactly as the CLI writes it.">
<link rel="canonical" href="https://ranwhat.com/example-report">
<link rel="icon" href="/favicon-32.png?v=2" sizes="32x32" type="image/png">"""

BANNER = ("<p style=\"margin:0 0 22px;font-size:13px;color:var(--muted)\">"
          "An example, not your data: this is what <code>uvx ranwhat demo "
          "--html report.html</code> writes for a bundled sample agent. "
          "<a style=\"color:var(--ink)\" href=\"/scan\">What the scores mean</a> &middot; "
          "<a style=\"color:var(--ink)\" href=\"/install\">Run it on your own</a></p>\n")

# The timestamp changes on every run and says nothing about the content.
GENERATED = re.compile(r"Generated [^<·]*·")


def build():
    argv, sys.argv = sys.argv, ["uvx ranwhat"]
    try:
        from ranwhat.cli import run_scan, _bundled
        from ranwhat.html_report import build_html
        html = build_html(run_scan(_bundled("support-copilot.json")))
    finally:
        sys.argv = argv
    html = GENERATED.sub("Generated by ranwhat demo ·", html)
    html = re.sub(r"<title>[^<]*</title>", lambda m: HEAD, html, count=1)
    return re.sub(r"(<body[^>]*>\s*(?:<div[^>]*>\s*)?)", lambda m: m.group(1) + BANNER,
                  html, count=1)


if __name__ == "__main__":
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(build())
    print("wrote", os.path.relpath(OUT, ROOT))
